services:
  main:
    image: jupyter/datascience-notebook
    container_name: julia
    user: root
    ports:
      - 8888:8888
    tty: true
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    
